### ISSUE TITLE
Impossible to create a new project.

### ISSUE THREAD

**Issue by Matthiasbrat** [max529/Aventus#1]
I'm trying to create a new project following the instructions on your website. I have installed the extension by dowloading the vsix file.
The error I get is :
`[Error - 09:41:02] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: EINVAL: invalid argument, mkdir 'file:///n%3A/3eme/Aventus/dist'
  Code: -32603 `

**Comment by max529** [comment]
Hi,
Thanks for the support but actually Aventus is a draft project, we will deploy a release soon so stay tuned.
If you want join the dev team, you can send me an email to maxime.betrisey@hotmail.com
